// Generated by gencpp from file rocon_interaction_msgs/GetPairingsResponse.msg
// DO NOT EDIT!


#ifndef ROCON_INTERACTION_MSGS_MESSAGE_GETPAIRINGSRESPONSE_H
#define ROCON_INTERACTION_MSGS_MESSAGE_GETPAIRINGSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rocon_interaction_msgs/Pairing.h>

namespace rocon_interaction_msgs
{
template <class ContainerAllocator>
struct GetPairingsResponse_
{
  typedef GetPairingsResponse_<ContainerAllocator> Type;

  GetPairingsResponse_()
    : pairings()  {
    }
  GetPairingsResponse_(const ContainerAllocator& _alloc)
    : pairings(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::rocon_interaction_msgs::Pairing_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::rocon_interaction_msgs::Pairing_<ContainerAllocator> >::other >  _pairings_type;
  _pairings_type pairings;




  typedef boost::shared_ptr< ::rocon_interaction_msgs::GetPairingsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rocon_interaction_msgs::GetPairingsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetPairingsResponse_

typedef ::rocon_interaction_msgs::GetPairingsResponse_<std::allocator<void> > GetPairingsResponse;

typedef boost::shared_ptr< ::rocon_interaction_msgs::GetPairingsResponse > GetPairingsResponsePtr;
typedef boost::shared_ptr< ::rocon_interaction_msgs::GetPairingsResponse const> GetPairingsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rocon_interaction_msgs::GetPairingsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rocon_interaction_msgs::GetPairingsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rocon_interaction_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'rocon_std_msgs': ['/home/giovani/catkin_ws/src/rocon_msgs/rocon_std_msgs/msg', '/home/giovani/catkin_ws/devel/share/rocon_std_msgs/msg'], 'rocon_service_pair_msgs': ['/home/giovani/catkin_ws/src/rocon_msgs/rocon_service_pair_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'rocon_interaction_msgs': ['/home/giovani/catkin_ws/src/rocon_msgs/rocon_interaction_msgs/msg'], 'uuid_msgs': ['/opt/ros/kinetic/share/uuid_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rocon_interaction_msgs::GetPairingsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rocon_interaction_msgs::GetPairingsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rocon_interaction_msgs::GetPairingsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rocon_interaction_msgs::GetPairingsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rocon_interaction_msgs::GetPairingsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rocon_interaction_msgs::GetPairingsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rocon_interaction_msgs::GetPairingsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d29a833c93f116257b8e089a802ebf98";
  }

  static const char* value(const ::rocon_interaction_msgs::GetPairingsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd29a833c93f11625ULL;
  static const uint64_t static_value2 = 0x7b8e089a802ebf98ULL;
};

template<class ContainerAllocator>
struct DataType< ::rocon_interaction_msgs::GetPairingsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rocon_interaction_msgs/GetPairingsResponse";
  }

  static const char* value(const ::rocon_interaction_msgs::GetPairingsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rocon_interaction_msgs::GetPairingsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Pairing[] pairings\n\
\n\
\n\
================================================================================\n\
MSG: rocon_interaction_msgs/Pairing\n\
###############################################################\n\
# Pairing rapp specification\n\
###############################################################\n\
\n\
# Unique name that represents this pairing. Note that you can\n\
# have multiple configurations of a single rapp, so the rapp\n\
# name alone is not enough to uniquely identify the pairing\n\
string name\n\
\n\
# Group to which this pairing belongs\n\
string group\n\
\n\
# ros resource name of the rapp, e.g. rocon_apps/talker\n\
string rapp\n\
\n\
###############################################################\n\
# Customising the rapp launch instance\n\
###############################################################\n\
\n\
# Can load the default rapp description, but sometimes useful to\n\
# override it to provide more human friendly information.\n\
string description\n\
\n\
# Whether or not this rapp should bringup/teardown an interaction\n\
# with the launching of this rapp. If empty, no interaction is\n\
# required, if non-empty, look for the specified interaction.\n\
string requires_interaction\n\
\n\
# Again, can load the default rapp icon, but may want to override it.\n\
rocon_std_msgs/Icon icon\n\
\n\
rocon_std_msgs/Remapping[] remappings\n\
\n\
# Key value pairs representing rapp parameters\n\
rocon_std_msgs/KeyValue[] parameters\n\
\n\
================================================================================\n\
MSG: rocon_std_msgs/Icon\n\
# Used to idenfity the original package/filename resource this icon was/is to be loaded from\n\
# This typically doesn't have to be set, but can be very useful when loading icons from yaml definitions.\n\
string resource_name\n\
\n\
# Image data format.  \"jpeg\" or \"png\"\n\
string format\n\
\n\
# Image data.\n\
uint8[] data\n\
================================================================================\n\
MSG: rocon_std_msgs/Remapping\n\
# Describes your typical ros remapping\n\
\n\
string remap_from\n\
string remap_to\n\
\n\
================================================================================\n\
MSG: rocon_std_msgs/KeyValue\n\
string key\n\
string value\n\
";
  }

  static const char* value(const ::rocon_interaction_msgs::GetPairingsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rocon_interaction_msgs::GetPairingsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pairings);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPairingsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rocon_interaction_msgs::GetPairingsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rocon_interaction_msgs::GetPairingsResponse_<ContainerAllocator>& v)
  {
    s << indent << "pairings[]" << std::endl;
    for (size_t i = 0; i < v.pairings.size(); ++i)
    {
      s << indent << "  pairings[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::rocon_interaction_msgs::Pairing_<ContainerAllocator> >::stream(s, indent + "    ", v.pairings[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROCON_INTERACTION_MSGS_MESSAGE_GETPAIRINGSRESPONSE_H
