// Generated by gencpp from file rocon_interaction_msgs/Interaction.msg
// DO NOT EDIT!


#ifndef ROCON_INTERACTION_MSGS_MESSAGE_INTERACTION_H
#define ROCON_INTERACTION_MSGS_MESSAGE_INTERACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rocon_std_msgs/Icon.h>
#include <rocon_std_msgs/Remapping.h>

namespace rocon_interaction_msgs
{
template <class ContainerAllocator>
struct Interaction_
{
  typedef Interaction_<ContainerAllocator> Type;

  Interaction_()
    : name()
    , command()
    , compatibility()
    , group()
    , description()
    , icon()
    , namespace()
    , remappings()
    , parameters()
    , max(0)
    , bringup_pairing(false)
    , teardown_pairing(false)
    , required_pairings()
    , hidden(false)
    , hash(0)  {
    }
  Interaction_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , command(_alloc)
    , compatibility(_alloc)
    , group(_alloc)
    , description(_alloc)
    , icon(_alloc)
    , namespace(_alloc)
    , remappings(_alloc)
    , parameters(_alloc)
    , max(0)
    , bringup_pairing(false)
    , teardown_pairing(false)
    , required_pairings(_alloc)
    , hidden(false)
    , hash(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  _command_type command;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _compatibility_type;
  _compatibility_type compatibility;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _group_type;
  _group_type group;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _description_type;
  _description_type description;

   typedef  ::rocon_std_msgs::Icon_<ContainerAllocator>  _icon_type;
  _icon_type icon;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _namespace_type;
  _namespace_type namespace;

   typedef std::vector< ::rocon_std_msgs::Remapping_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::rocon_std_msgs::Remapping_<ContainerAllocator> >::other >  _remappings_type;
  _remappings_type remappings;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _parameters_type;
  _parameters_type parameters;

   typedef int32_t _max_type;
  _max_type max;

   typedef uint8_t _bringup_pairing_type;
  _bringup_pairing_type bringup_pairing;

   typedef uint8_t _teardown_pairing_type;
  _teardown_pairing_type teardown_pairing;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _required_pairings_type;
  _required_pairings_type required_pairings;

   typedef uint8_t _hidden_type;
  _hidden_type hidden;

   typedef int32_t _hash_type;
  _hash_type hash;


    enum { UNLIMITED_INTERACTIONS = -1 };
 

  typedef boost::shared_ptr< ::rocon_interaction_msgs::Interaction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rocon_interaction_msgs::Interaction_<ContainerAllocator> const> ConstPtr;

}; // struct Interaction_

typedef ::rocon_interaction_msgs::Interaction_<std::allocator<void> > Interaction;

typedef boost::shared_ptr< ::rocon_interaction_msgs::Interaction > InteractionPtr;
typedef boost::shared_ptr< ::rocon_interaction_msgs::Interaction const> InteractionConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rocon_interaction_msgs::Interaction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rocon_interaction_msgs::Interaction_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rocon_interaction_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'rocon_std_msgs': ['/home/giovani/catkin_ws/src/rocon_msgs/rocon_std_msgs/msg', '/home/giovani/catkin_ws/devel/share/rocon_std_msgs/msg'], 'rocon_service_pair_msgs': ['/home/giovani/catkin_ws/src/rocon_msgs/rocon_service_pair_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'rocon_interaction_msgs': ['/home/giovani/catkin_ws/src/rocon_msgs/rocon_interaction_msgs/msg'], 'uuid_msgs': ['/opt/ros/kinetic/share/uuid_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rocon_interaction_msgs::Interaction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rocon_interaction_msgs::Interaction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rocon_interaction_msgs::Interaction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rocon_interaction_msgs::Interaction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rocon_interaction_msgs::Interaction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rocon_interaction_msgs::Interaction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rocon_interaction_msgs::Interaction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "654684c49f3d36d7af7c76c44f9b80e4";
  }

  static const char* value(const ::rocon_interaction_msgs::Interaction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x654684c49f3d36d7ULL;
  static const uint64_t static_value2 = 0xaf7c76c44f9b80e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::rocon_interaction_msgs::Interaction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rocon_interaction_msgs/Interaction";
  }

  static const char* value(const ::rocon_interaction_msgs::Interaction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rocon_interaction_msgs::Interaction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "###############################################################\n\
# Required Specifications\n\
###############################################################\n\
\n\
# User friendly version of the name. Useful to be customised\n\
# differently from the name for either 1) branding, or 2) because\n\
# some names are complicated visually (e.g. android names).\n\
string name\n\
\n\
# This should be the string required to install and execute\n\
# the interaction from a remocon. \n\
# - android app : the intent action name (e.g. com.github.rosjava.android_apps.listener.Listener)\n\
# - web app : the url\n\
# - roslaunch : package resource name (e.g. gopher_meta/minimal.launch)\n\
# - rosrun : package resource name (e.g. gopher_meta/enable_motors)\n\
# - global : just the executable (e.g. rocon_master_info)\n\
string command\n\
\n\
# A rocon uri string denoting the platforms this interaction\n\
# is compatible with\n\
string compatibility\n\
\n\
###############################################################\n\
# Optional Specifications\n\
###############################################################\n\
\n\
# The group this solution has configured the interaction for.\n\
string group\n\
\n\
# Should be a default for the interaction, but sometimes useful to\n\
# override it to provide more human friendly information.\n\
string description\n\
\n\
# Again, should exist a default, but may want to override it.\n\
rocon_std_msgs/Icon icon\n\
\n\
# The namespace that this interaction will be associated\n\
# with. Interfaces from the interaction will be automatically pushed\n\
# into this namespace (for concerts it will be typically\n\
# used by the services to push interfaces into /services/_service_name_).\n\
# It is up to the user to make sure this is unique to avoid\n\
# potential conflicts.\n\
string namespace\n\
\n\
# Any remappings that need to be applied\n\
rocon_std_msgs/Remapping[] remappings\n\
\n\
# Yaml string representing parameters for the interaction\n\
string parameters\n\
\n\
# Maximum number of permitted connections (-1 = any)\n\
int32 UNLIMITED_INTERACTIONS = -1\n\
int32 max\n\
\n\
# If it should be paired with launch configurations via rapps\n\
bool bringup_pairing\n\
bool teardown_pairing\n\
string[] required_pairings\n\
\n\
# whether it should be a hidden icon in a remocon\n\
bool hidden\n\
\n\
###############################################################\n\
# Parameters finalised by the interactions manager\n\
###############################################################\n\
\n\
# This is a crc32 hash code for the name-group-command\n\
# triple that uniquely identifies this interaction.\n\
# crc32 gets a few collisions, so we should be careful of that.\n\
# It is used by the nfc android auto-launching program so we can\n\
# compactify the request in the url sent by the nfc to the autolauncher.\n\
int32 hash\n\
\n\
\n\
================================================================================\n\
MSG: rocon_std_msgs/Icon\n\
# Used to idenfity the original package/filename resource this icon was/is to be loaded from\n\
# This typically doesn't have to be set, but can be very useful when loading icons from yaml definitions.\n\
string resource_name\n\
\n\
# Image data format.  \"jpeg\" or \"png\"\n\
string format\n\
\n\
# Image data.\n\
uint8[] data\n\
================================================================================\n\
MSG: rocon_std_msgs/Remapping\n\
# Describes your typical ros remapping\n\
\n\
string remap_from\n\
string remap_to\n\
";
  }

  static const char* value(const ::rocon_interaction_msgs::Interaction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rocon_interaction_msgs::Interaction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.command);
      stream.next(m.compatibility);
      stream.next(m.group);
      stream.next(m.description);
      stream.next(m.icon);
      stream.next(m.namespace);
      stream.next(m.remappings);
      stream.next(m.parameters);
      stream.next(m.max);
      stream.next(m.bringup_pairing);
      stream.next(m.teardown_pairing);
      stream.next(m.required_pairings);
      stream.next(m.hidden);
      stream.next(m.hash);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Interaction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rocon_interaction_msgs::Interaction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rocon_interaction_msgs::Interaction_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
    s << indent << "compatibility: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.compatibility);
    s << indent << "group: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.group);
    s << indent << "description: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.description);
    s << indent << "icon: ";
    s << std::endl;
    Printer< ::rocon_std_msgs::Icon_<ContainerAllocator> >::stream(s, indent + "  ", v.icon);
    s << indent << "namespace: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.namespace);
    s << indent << "remappings[]" << std::endl;
    for (size_t i = 0; i < v.remappings.size(); ++i)
    {
      s << indent << "  remappings[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::rocon_std_msgs::Remapping_<ContainerAllocator> >::stream(s, indent + "    ", v.remappings[i]);
    }
    s << indent << "parameters: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.parameters);
    s << indent << "max: ";
    Printer<int32_t>::stream(s, indent + "  ", v.max);
    s << indent << "bringup_pairing: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bringup_pairing);
    s << indent << "teardown_pairing: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.teardown_pairing);
    s << indent << "required_pairings[]" << std::endl;
    for (size_t i = 0; i < v.required_pairings.size(); ++i)
    {
      s << indent << "  required_pairings[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.required_pairings[i]);
    }
    s << indent << "hidden: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hidden);
    s << indent << "hash: ";
    Printer<int32_t>::stream(s, indent + "  ", v.hash);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROCON_INTERACTION_MSGS_MESSAGE_INTERACTION_H
