// Generated by gencpp from file rocon_interaction_msgs/StartPairing.msg
// DO NOT EDIT!


#ifndef ROCON_INTERACTION_MSGS_MESSAGE_STARTPAIRING_H
#define ROCON_INTERACTION_MSGS_MESSAGE_STARTPAIRING_H

#include <ros/service_traits.h>


#include <rocon_interaction_msgs/StartPairingRequest.h>
#include <rocon_interaction_msgs/StartPairingResponse.h>


namespace rocon_interaction_msgs
{

struct StartPairing
{

typedef StartPairingRequest Request;
typedef StartPairingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartPairing
} // namespace rocon_interaction_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rocon_interaction_msgs::StartPairing > {
  static const char* value()
  {
    return "f4f70c3c5d522bf6827d164317046e04";
  }

  static const char* value(const ::rocon_interaction_msgs::StartPairing&) { return value(); }
};

template<>
struct DataType< ::rocon_interaction_msgs::StartPairing > {
  static const char* value()
  {
    return "rocon_interaction_msgs/StartPairing";
  }

  static const char* value(const ::rocon_interaction_msgs::StartPairing&) { return value(); }
};


// service_traits::MD5Sum< ::rocon_interaction_msgs::StartPairingRequest> should match 
// service_traits::MD5Sum< ::rocon_interaction_msgs::StartPairing > 
template<>
struct MD5Sum< ::rocon_interaction_msgs::StartPairingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rocon_interaction_msgs::StartPairing >::value();
  }
  static const char* value(const ::rocon_interaction_msgs::StartPairingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rocon_interaction_msgs::StartPairingRequest> should match 
// service_traits::DataType< ::rocon_interaction_msgs::StartPairing > 
template<>
struct DataType< ::rocon_interaction_msgs::StartPairingRequest>
{
  static const char* value()
  {
    return DataType< ::rocon_interaction_msgs::StartPairing >::value();
  }
  static const char* value(const ::rocon_interaction_msgs::StartPairingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rocon_interaction_msgs::StartPairingResponse> should match 
// service_traits::MD5Sum< ::rocon_interaction_msgs::StartPairing > 
template<>
struct MD5Sum< ::rocon_interaction_msgs::StartPairingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rocon_interaction_msgs::StartPairing >::value();
  }
  static const char* value(const ::rocon_interaction_msgs::StartPairingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rocon_interaction_msgs::StartPairingResponse> should match 
// service_traits::DataType< ::rocon_interaction_msgs::StartPairing > 
template<>
struct DataType< ::rocon_interaction_msgs::StartPairingResponse>
{
  static const char* value()
  {
    return DataType< ::rocon_interaction_msgs::StartPairing >::value();
  }
  static const char* value(const ::rocon_interaction_msgs::StartPairingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROCON_INTERACTION_MSGS_MESSAGE_STARTPAIRING_H
