// Generated by gencpp from file rocon_interaction_msgs/StopPairing.msg
// DO NOT EDIT!


#ifndef ROCON_INTERACTION_MSGS_MESSAGE_STOPPAIRING_H
#define ROCON_INTERACTION_MSGS_MESSAGE_STOPPAIRING_H

#include <ros/service_traits.h>


#include <rocon_interaction_msgs/StopPairingRequest.h>
#include <rocon_interaction_msgs/StopPairingResponse.h>


namespace rocon_interaction_msgs
{

struct StopPairing
{

typedef StopPairingRequest Request;
typedef StopPairingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopPairing
} // namespace rocon_interaction_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rocon_interaction_msgs::StopPairing > {
  static const char* value()
  {
    return "f4f70c3c5d522bf6827d164317046e04";
  }

  static const char* value(const ::rocon_interaction_msgs::StopPairing&) { return value(); }
};

template<>
struct DataType< ::rocon_interaction_msgs::StopPairing > {
  static const char* value()
  {
    return "rocon_interaction_msgs/StopPairing";
  }

  static const char* value(const ::rocon_interaction_msgs::StopPairing&) { return value(); }
};


// service_traits::MD5Sum< ::rocon_interaction_msgs::StopPairingRequest> should match 
// service_traits::MD5Sum< ::rocon_interaction_msgs::StopPairing > 
template<>
struct MD5Sum< ::rocon_interaction_msgs::StopPairingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rocon_interaction_msgs::StopPairing >::value();
  }
  static const char* value(const ::rocon_interaction_msgs::StopPairingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rocon_interaction_msgs::StopPairingRequest> should match 
// service_traits::DataType< ::rocon_interaction_msgs::StopPairing > 
template<>
struct DataType< ::rocon_interaction_msgs::StopPairingRequest>
{
  static const char* value()
  {
    return DataType< ::rocon_interaction_msgs::StopPairing >::value();
  }
  static const char* value(const ::rocon_interaction_msgs::StopPairingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rocon_interaction_msgs::StopPairingResponse> should match 
// service_traits::MD5Sum< ::rocon_interaction_msgs::StopPairing > 
template<>
struct MD5Sum< ::rocon_interaction_msgs::StopPairingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rocon_interaction_msgs::StopPairing >::value();
  }
  static const char* value(const ::rocon_interaction_msgs::StopPairingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rocon_interaction_msgs::StopPairingResponse> should match 
// service_traits::DataType< ::rocon_interaction_msgs::StopPairing > 
template<>
struct DataType< ::rocon_interaction_msgs::StopPairingResponse>
{
  static const char* value()
  {
    return DataType< ::rocon_interaction_msgs::StopPairing >::value();
  }
  static const char* value(const ::rocon_interaction_msgs::StopPairingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROCON_INTERACTION_MSGS_MESSAGE_STOPPAIRING_H
