(cl:in-package rocon_interaction_msgs-msg)
(cl:export '(NAME-VAL
          NAME
          COMMAND-VAL
          COMMAND
          COMPATIBILITY-VAL
          COMPATIBILITY
          GROUP-VAL
          GROUP
          DESCRIPTION-VAL
          DESCRIPTION
          ICON-VAL
          ICON
          NAMESPACE-VAL
          NAMESPACE
          REMAPPINGS-VAL
          REMAPPINGS
          PARAMETERS-VAL
          PARAMETERS
          MAX-VAL
          MAX
          BRINGUP_PAIRING-VAL
          BRINGUP_PAIRING
          TEARDOWN_PAIRING-VAL
          TEARDOWN_PAIRING
          REQUIRED_PAIRINGS-VAL
          REQUIRED_PAIRINGS
          HIDDEN-VAL
          HIDDEN
          HASH-VAL
          HASH
))