(cl:defpackage rocon_interaction_msgs-msg
  (:use )
  (:export
   "<ERRORCODES>"
   "ERRORCODES"
   "<INTERACTION>"
   "INTERACTION"
   "<INTERACTIVECLIENT>"
   "INTERACTIVECLIENT"
   "<INTERACTIVECLIENTS>"
   "INTERACTIVECLIENTS"
   "<PAIRING>"
   "PAIRING"
   "<PAIRINGSTATUS>"
   "PAIRINGSTATUS"
   "<REMOCONSTATUS>"
   "REMOCONSTATUS"
   "<STRINGS>"
   "STRINGS"
  ))

