// Auto-generated. Do not edit!

// (in-package rocon_service_pair_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let TestiesResponse = require('./TestiesResponse.js');
let uuid_msgs = _finder('uuid_msgs');

//-----------------------------------------------------------

class TestiesPairResponse {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.id = null;
      this.response = null;
    }
    else {
      if (initObj.hasOwnProperty('id')) {
        this.id = initObj.id
      }
      else {
        this.id = new uuid_msgs.msg.UniqueID();
      }
      if (initObj.hasOwnProperty('response')) {
        this.response = initObj.response
      }
      else {
        this.response = new TestiesResponse();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type TestiesPairResponse
    // Serialize message field [id]
    bufferOffset = uuid_msgs.msg.UniqueID.serialize(obj.id, buffer, bufferOffset);
    // Serialize message field [response]
    bufferOffset = TestiesResponse.serialize(obj.response, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type TestiesPairResponse
    let len;
    let data = new TestiesPairResponse(null);
    // Deserialize message field [id]
    data.id = uuid_msgs.msg.UniqueID.deserialize(buffer, bufferOffset);
    // Deserialize message field [response]
    data.response = TestiesResponse.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += TestiesResponse.getMessageSize(object.response);
    return length + 16;
  }

  static datatype() {
    // Returns string type for a message object
    return 'rocon_service_pair_msgs/TestiesPairResponse';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '05404c9fe275eda57650fdfced8cf402';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    uuid_msgs/UniqueID id
    TestiesResponse response
    
    ================================================================================
    MSG: uuid_msgs/UniqueID
    # A universally unique identifier (UUID).
    #
    #  http://en.wikipedia.org/wiki/Universally_unique_identifier
    #  http://tools.ietf.org/html/rfc4122.html
    
    uint8[16] uuid
    
    ================================================================================
    MSG: rocon_service_pair_msgs/TestiesResponse
    # ====== DO NOT MODIFY! AUTOGENERATED FROM A SERVICE PAIR DEFINITION ======
    uuid_msgs/UniqueID id
    string data
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new TestiesPairResponse(null);
    if (msg.id !== undefined) {
      resolved.id = uuid_msgs.msg.UniqueID.Resolve(msg.id)
    }
    else {
      resolved.id = new uuid_msgs.msg.UniqueID()
    }

    if (msg.response !== undefined) {
      resolved.response = TestiesResponse.Resolve(msg.response)
    }
    else {
      resolved.response = new TestiesResponse()
    }

    return resolved;
    }
};

module.exports = TestiesPairResponse;
