// Generated by gencpp from file etrans_msgs/etrans_intersection.msg
// DO NOT EDIT!


#ifndef ETRANS_MSGS_MESSAGE_ETRANS_INTERSECTION_H
#define ETRANS_MSGS_MESSAGE_ETRANS_INTERSECTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <etrans_msgs/etrans_light.h>
#include <etrans_msgs/etrans_lane.h>

namespace etrans_msgs
{
template <class ContainerAllocator>
struct etrans_intersection_
{
  typedef etrans_intersection_<ContainerAllocator> Type;

  etrans_intersection_()
    : header()
    , ID(0)
    , lights()
    , lanes()  {
    }
  etrans_intersection_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ID(0)
    , lights(_alloc)
    , lanes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _ID_type;
  _ID_type ID;

   typedef std::vector< ::etrans_msgs::etrans_light_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::etrans_msgs::etrans_light_<ContainerAllocator> >::other >  _lights_type;
  _lights_type lights;

   typedef std::vector< ::etrans_msgs::etrans_lane_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::etrans_msgs::etrans_lane_<ContainerAllocator> >::other >  _lanes_type;
  _lanes_type lanes;




  typedef boost::shared_ptr< ::etrans_msgs::etrans_intersection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::etrans_msgs::etrans_intersection_<ContainerAllocator> const> ConstPtr;

}; // struct etrans_intersection_

typedef ::etrans_msgs::etrans_intersection_<std::allocator<void> > etrans_intersection;

typedef boost::shared_ptr< ::etrans_msgs::etrans_intersection > etrans_intersectionPtr;
typedef boost::shared_ptr< ::etrans_msgs::etrans_intersection const> etrans_intersectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::etrans_msgs::etrans_intersection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::etrans_msgs::etrans_intersection_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace etrans_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'etrans_msgs': ['/home/wqkhan/catkin_ws/src/renesas-demo/drivers/third_party/etrans_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::etrans_msgs::etrans_intersection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::etrans_msgs::etrans_intersection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::etrans_msgs::etrans_intersection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::etrans_msgs::etrans_intersection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::etrans_msgs::etrans_intersection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::etrans_msgs::etrans_intersection_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::etrans_msgs::etrans_intersection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0c97a642a195257607a5e8b421317b71";
  }

  static const char* value(const ::etrans_msgs::etrans_intersection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0c97a642a1952576ULL;
  static const uint64_t static_value2 = 0x07a5e8b421317b71ULL;
};

template<class ContainerAllocator>
struct DataType< ::etrans_msgs::etrans_intersection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "etrans_msgs/etrans_intersection";
  }

  static const char* value(const ::etrans_msgs::etrans_intersection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::etrans_msgs::etrans_intersection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
uint32 ID\n\
etrans_msgs/etrans_light[] lights\n\
etrans_msgs/etrans_lane[] lanes\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: etrans_msgs/etrans_light\n\
int8 state\n\
uint32 signal_group\n\
float64 time_to_change\n\
float64 latitude\n\
float64 longitude\n\
\n\
================================================================================\n\
MSG: etrans_msgs/etrans_lane\n\
uint32 ID\n\
etrans_msgs/etrans_latlon[] centerpoints\n\
================================================================================\n\
MSG: etrans_msgs/etrans_latlon\n\
float64 latitude\n\
float64 longitude\n\
";
  }

  static const char* value(const ::etrans_msgs::etrans_intersection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::etrans_msgs::etrans_intersection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ID);
      stream.next(m.lights);
      stream.next(m.lanes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct etrans_intersection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::etrans_msgs::etrans_intersection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::etrans_msgs::etrans_intersection_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ID: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.ID);
    s << indent << "lights[]" << std::endl;
    for (size_t i = 0; i < v.lights.size(); ++i)
    {
      s << indent << "  lights[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::etrans_msgs::etrans_light_<ContainerAllocator> >::stream(s, indent + "    ", v.lights[i]);
    }
    s << indent << "lanes[]" << std::endl;
    for (size_t i = 0; i < v.lanes.size(); ++i)
    {
      s << indent << "  lanes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::etrans_msgs::etrans_lane_<ContainerAllocator> >::stream(s, indent + "    ", v.lanes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ETRANS_MSGS_MESSAGE_ETRANS_INTERSECTION_H
