// Generated by gencpp from file etrans_msgs/etrans_latlon.msg
// DO NOT EDIT!


#ifndef ETRANS_MSGS_MESSAGE_ETRANS_LATLON_H
#define ETRANS_MSGS_MESSAGE_ETRANS_LATLON_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace etrans_msgs
{
template <class ContainerAllocator>
struct etrans_latlon_
{
  typedef etrans_latlon_<ContainerAllocator> Type;

  etrans_latlon_()
    : latitude(0.0)
    , longitude(0.0)  {
    }
  etrans_latlon_(const ContainerAllocator& _alloc)
    : latitude(0.0)
    , longitude(0.0)  {
  (void)_alloc;
    }



   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;




  typedef boost::shared_ptr< ::etrans_msgs::etrans_latlon_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::etrans_msgs::etrans_latlon_<ContainerAllocator> const> ConstPtr;

}; // struct etrans_latlon_

typedef ::etrans_msgs::etrans_latlon_<std::allocator<void> > etrans_latlon;

typedef boost::shared_ptr< ::etrans_msgs::etrans_latlon > etrans_latlonPtr;
typedef boost::shared_ptr< ::etrans_msgs::etrans_latlon const> etrans_latlonConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::etrans_msgs::etrans_latlon_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::etrans_msgs::etrans_latlon_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace etrans_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'etrans_msgs': ['/home/waleedqk/catkin_ws/src/renesas-demo/drivers/third_party/etrans_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::etrans_msgs::etrans_latlon_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::etrans_msgs::etrans_latlon_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::etrans_msgs::etrans_latlon_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::etrans_msgs::etrans_latlon_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::etrans_msgs::etrans_latlon_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::etrans_msgs::etrans_latlon_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::etrans_msgs::etrans_latlon_<ContainerAllocator> >
{
  static const char* value()
  {
    return "680c6dc7da65a2421a822205dcbdb600";
  }

  static const char* value(const ::etrans_msgs::etrans_latlon_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x680c6dc7da65a242ULL;
  static const uint64_t static_value2 = 0x1a822205dcbdb600ULL;
};

template<class ContainerAllocator>
struct DataType< ::etrans_msgs::etrans_latlon_<ContainerAllocator> >
{
  static const char* value()
  {
    return "etrans_msgs/etrans_latlon";
  }

  static const char* value(const ::etrans_msgs::etrans_latlon_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::etrans_msgs::etrans_latlon_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 latitude\n\
float64 longitude\n\
";
  }

  static const char* value(const ::etrans_msgs::etrans_latlon_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::etrans_msgs::etrans_latlon_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude);
      stream.next(m.longitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct etrans_latlon_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::etrans_msgs::etrans_latlon_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::etrans_msgs::etrans_latlon_<ContainerAllocator>& v)
  {
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ETRANS_MSGS_MESSAGE_ETRANS_LATLON_H
