# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from etrans_msgs/etrans_lane.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import etrans_msgs.msg

class etrans_lane(genpy.Message):
  _md5sum = "af8c9fbac78c2f807829637ebfead832"
  _type = "etrans_msgs/etrans_lane"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint32 ID
etrans_msgs/etrans_latlon[] centerpoints
================================================================================
MSG: etrans_msgs/etrans_latlon
float64 latitude
float64 longitude"""
  __slots__ = ['ID','centerpoints']
  _slot_types = ['uint32','etrans_msgs/etrans_latlon[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ID,centerpoints

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(etrans_lane, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.ID is None:
        self.ID = 0
      if self.centerpoints is None:
        self.centerpoints = []
    else:
      self.ID = 0
      self.centerpoints = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_I().pack(self.ID))
      length = len(self.centerpoints)
      buff.write(_struct_I.pack(length))
      for val1 in self.centerpoints:
        _x = val1
        buff.write(_get_struct_2d().pack(_x.latitude, _x.longitude))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.centerpoints is None:
        self.centerpoints = None
      end = 0
      start = end
      end += 4
      (self.ID,) = _get_struct_I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.centerpoints = []
      for i in range(0, length):
        val1 = etrans_msgs.msg.etrans_latlon()
        _x = val1
        start = end
        end += 16
        (_x.latitude, _x.longitude,) = _get_struct_2d().unpack(str[start:end])
        self.centerpoints.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_get_struct_I().pack(self.ID))
      length = len(self.centerpoints)
      buff.write(_struct_I.pack(length))
      for val1 in self.centerpoints:
        _x = val1
        buff.write(_get_struct_2d().pack(_x.latitude, _x.longitude))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.centerpoints is None:
        self.centerpoints = None
      end = 0
      start = end
      end += 4
      (self.ID,) = _get_struct_I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.centerpoints = []
      for i in range(0, length):
        val1 = etrans_msgs.msg.etrans_latlon()
        _x = val1
        start = end
        end += 16
        (_x.latitude, _x.longitude,) = _get_struct_2d().unpack(str[start:end])
        self.centerpoints.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2d = None
def _get_struct_2d():
    global _struct_2d
    if _struct_2d is None:
        _struct_2d = struct.Struct("<2d")
    return _struct_2d
