(cl:in-package anm_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ID-VAL
          ID
          LABELS-VAL
          LABELS
          CENTER-VAL
          CENTER
          H-VAL
          H
          W-VAL
          W
          L-VAL
          L
          RY-VAL
          RY
          SCORE-VAL
          SCORE
          VELOCITY-VAL
          VELOCITY
          OCCLUDED-VAL
          OCCLUDED
          HISTORIED_CENTER-VAL
          HISTORIED_CENTER
          HISTORIED_VELOCITY-VAL
          HISTORIED_VELOCITY
          HISTORIED_OCCLUDED-VAL
          HISTORIED_OCCLUDED
))