(cl:in-package zeroconf_msgs-msg)
(cl:export '(NAME-VAL
          NAME
          TYPE-VAL
          TYPE
          DOMAIN-VAL
          DOMAIN
          DESCRIPTION-VAL
          DESCRIPTION
          HOSTNAME-VAL
          HOSTNAME
          IPV4_ADDRESSES-VAL
          IPV4_ADDRESSES
          IPV6_ADDRESSES-VAL
          IPV6_ADDRESSES
          PORT-VAL
          PORT
          COOKIE-VAL
          COOKIE
          IS_LOCAL-VAL
          IS_LOCAL
          OUR_OWN-VAL
          OUR_OWN
          WIDE_AREA-VAL
          WIDE_AREA
          MULTICAST-VAL
          MULTICAST
          CACHED-VAL
          CACHED
))