# THIS ENTIRE MESSAGE NOT AVAILABLE FOR CES 2018

# 3-D Bounding Box

# bottom left corner of bounding box nearest to camera
rea_perception_msgs/rea_perception_xyz bottom_left

# Top right corner of bounding box nearest to camera
rea_perception_msgs/rea_perception_xyz top_right

# Offset to get to far away bounding box
rea_perception_msgs/rea_perception_xyz delta

# Yaw in radians w.r.t. center of object
# VALUE NOT AVAILABLE FOR CES 2018
int32 yaw

# How confident we are of the object existing in this box
uint32 confidence
