// Generated by gencpp from file anm_msgs/RODElement.msg
// DO NOT EDIT!


#ifndef ANM_MSGS_MESSAGE_RODELEMENT_H
#define ANM_MSGS_MESSAGE_RODELEMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace anm_msgs
{
template <class ContainerAllocator>
struct RODElement_
{
  typedef RODElement_<ContainerAllocator> Type;

  RODElement_()
    : header()
    , element_type()
    , float_value(0.0)
    , string_value()
    , string_array()  {
    }
  RODElement_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , element_type(_alloc)
    , float_value(0.0)
    , string_value(_alloc)
    , string_array(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _element_type_type;
  _element_type_type element_type;

   typedef float _float_value_type;
  _float_value_type float_value;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _string_value_type;
  _string_value_type string_value;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _string_array_type;
  _string_array_type string_array;




  typedef boost::shared_ptr< ::anm_msgs::RODElement_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::anm_msgs::RODElement_<ContainerAllocator> const> ConstPtr;

}; // struct RODElement_

typedef ::anm_msgs::RODElement_<std::allocator<void> > RODElement;

typedef boost::shared_ptr< ::anm_msgs::RODElement > RODElementPtr;
typedef boost::shared_ptr< ::anm_msgs::RODElement const> RODElementConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::anm_msgs::RODElement_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::anm_msgs::RODElement_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace anm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'anm_msgs': ['/home/waleedqk/catkin_ws/src/renesas-demo/autonomoose/rospackages/autonomoose_core/anm_msgs/msg'], 'dbw_mkz_msgs': ['/home/waleedqk/catkin_ws/deploy/install/opt/ros/fisch/share/dbw_mkz_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::anm_msgs::RODElement_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anm_msgs::RODElement_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::anm_msgs::RODElement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::anm_msgs::RODElement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anm_msgs::RODElement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anm_msgs::RODElement_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::anm_msgs::RODElement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b81e47d437c4534e895e59adcc7f186";
  }

  static const char* value(const ::anm_msgs::RODElement_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b81e47d437c4534ULL;
  static const uint64_t static_value2 = 0xe895e59adcc7f186ULL;
};

template<class ContainerAllocator>
struct DataType< ::anm_msgs::RODElement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "anm_msgs/RODElement";
  }

  static const char* value(const ::anm_msgs::RODElement_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::anm_msgs::RODElement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
# Type/classification of element\n\
string element_type\n\
\n\
# Different values depending on the element type\n\
float32 float_value\n\
string string_value\n\
string[] string_array\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::anm_msgs::RODElement_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::anm_msgs::RODElement_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.element_type);
      stream.next(m.float_value);
      stream.next(m.string_value);
      stream.next(m.string_array);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RODElement_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::anm_msgs::RODElement_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::anm_msgs::RODElement_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "element_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.element_type);
    s << indent << "float_value: ";
    Printer<float>::stream(s, indent + "  ", v.float_value);
    s << indent << "string_value: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.string_value);
    s << indent << "string_array[]" << std::endl;
    for (size_t i = 0; i < v.string_array.size(); ++i)
    {
      s << indent << "  string_array[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.string_array[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANM_MSGS_MESSAGE_RODELEMENT_H
